services:
  nuxt:
    build: .
    ports:
      - "3000"
    networks:
      - app_network
    env_file:
      - .env
    deploy:
      replicas: 3
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - app_network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nuxt
    restart: unless-stopped

networks:
  app_network:  
    driver: bridge