services:
  nuxt1:
    build: .
    environment:
      - NITRO_PORT=3000
    expose:
      - "3000"
    env_file:
      - .env

  nuxt2:
    build: .
    environment:
      - NITRO_PORT=3001
    expose:
      - "3001"
    env_file:
      - .env

  nuxt3:
    build: .
    environment:
      - NITRO_PORT=3002
    expose:
      - "3002"
    env_file:
      - .env
      
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nuxt1
      - nuxt2
      - nuxt3